### ISSUE TITLE
[Help needed] Problems in changing underlying TableViewCell label

### ISSUE THREAD

**Issue by karstengresch** [bcylin/QuickTableViewController#12]
Thanks for this wonderful project first - seems to make life much easier!

I'd like to color the labels of _QuickTableViewController_'s rows, but can't get it to work.

Though I'm able applying a general style in _AppDelegate_ with...

```swift
  let tableViewCellLabelAppearance = UILabel.appearance(whenContainedInInstancesOf: [UITableViewCell.self])
  tableViewCellLabelAppearance.textColor = Theme.textColor
``` 

...all other labels in all other TableViewCells get colored accordingly, except of those from _QuickTableViewController_.

My naive approach to get this working was...

```swift
  let optionRowLabelAppearance = UILabel.appearance(whenContainedInInstancesOf: [OptionRow.self])
  optionRowLabelAppearance.textColor = Theme.textColor
```

...but this was refused with the compiler error message:

_Cannot convert value of type 'OptionRow<UITableViewCell'>.Type to expected element type 'UIAppearanceContainerType'_

Wondering now what the preferred way is theming QuickTableViewController views?

Thanks and best wishes,

Karsten

**Comment by bcylin** [comment]
Hi Karsten,

Thanks for the feedback. The label is contained in the associated `UITableViewCell`, instead of `OptionRow` itself. To fix the compiler error, it should be:

```swift
// When it's OptionRow<CustomOptionCell>
let optionRowLabelAppearance = UILabel.appearance(whenContainedInInstancesOf: [CustomOptionCell.self])
optionRowLabelAppearance.textColor = Theme.textColor
```

## UIAppearance issue

I find that `UILabel.appearance(whenContainedInInstancesOf: [UITableViewCell.self])` works alright when the cell is dequeued with an identifier set in the storyboard.

But somehow it doesn't work when the cell is either registered with a class:

```swift
tableView.register(UITableViewCell.self, forCellReuseIdentifier: "reuseIdentifier")
```

or is initialized in code:

```swift
let cell = UITableViewCell(style: .subtitle, reuseIdentifier: "reuseIdentifier")
```

Since `QuickTableViewController` initializes table view cells in code without using a storyboard, the labels don't pick up the appearance settings in the cells. One way to work around this issue might be registering a nib object.

## Workaround with a nib object

Add a `CustomOptionCell.xib`:

1. drag in a **Table View Cell** object to replace the default view
2. set its **Style** to Basic or Subtitle
3. set the **Custom Class** to `CustomOptionCell`
4. set the reuse identifier to `CustomOptionCell`, same as the type name

Register the nib to the table view with:

```swift
class CustomOptionCell: UITableViewCell {}
```
```swift
let typeName = "CustomOptionCell"
tableView.register(UINib(nibName: typeName, bundle: .main), forCellReuseIdentifier: typeName)
```

Instead of using the default `OptionRow` in the section, specify the associated cell type `OptionRow<CustomOptionCell>`.

Then the table view will dequeue the cell registered in the nib and the `UIAppearance` customization should work in those cells. Hope this helps.

**Comment by karstengresch** [comment]
Hi Ben,

thanks for your quick answer. So much appreciated!

>Then the table view will dequeue the cell registered in the nib and the UIAppearance customization should work in those cells. 
>Hope this helps.
This indeed helped and I could successfully change the label color 👍 

Unfortunately, the problem remains with _SwitchCell_ and _TapActionCell_ - got stuck creating a xib file directly using _TapActionCell_ eg.

There should be an easier way to get the labels styled (maybe using 

```swift
public init(style: UITableViewCellStyle, reuseIdentifier: String?)
```
? But I'm not really sure, how.

Any idea at your side?

Best wishes,

Karsten

**Comment by bcylin** [comment]
Hi Karsten,

I tried it on the Example app.
https://github.com/bcylin/QuickTableViewController/compare/feature/ui-appearance

Although `TapActionCell` sets its text color during initialization, it seems no problem with the UIAppearance `textColor` on iOS 11.2 simulator.
