### ISSUE TITLE
Duplicate sections over table

### ISSUE THREAD

**Issue by mirkin** [bcylin/QuickTableViewController#15]
I'm getting duplicate sections overlaid on top of the table as it scrolls.

![img_0278](https://user-images.githubusercontent.com/3847771/39578908-60bfa4f2-4edd-11e8-8e78-163bec2e5e8a.GIF)

**Comment by mirkin** [comment]
The code is the same as your sample code but the table is in a Navigation Controller in the storyboard.

**Comment by bcylin** [comment]
I tried it with a navigation controller in the storyboard. It works alright. I might need more info to look into this issue if you don't mind sharing a single-view app xcodeproj with your configuration.

**Comment by mirkin** [comment]
Thanks, I've attached a simple project. It's possibly because I'm going about things the wrong way as the problem only arises any time I try to use it  in a more complex view.

What would be the best route to include your QuickTableViewController in the storyboard for a View with other UI elements as well as the table?

[QuickTableViewTest.zip](https://github.com/bcylin/QuickTableViewController/files/1983332/QuickTableViewTest.zip)

**Comment by mirkin** [comment]
OK I think this is down to using UITableViews in the Storyboard, I should be using regular views.

**Comment by bcylin** [comment]
Hi @mirkin, sorry for the late reply. I took a look at the project you uploaded. There are two table views in the view hierarchy. One is inherited from `QuickTableViewController`, the other is added inside the storyboard. Both of their data sources are pointing to your view controller. I suppose that's why you saw duplicate section headers.

If you delete the additional table view from the storyboard and let `QuickTableViewController` handles the table view, it should work fine.
