### ISSUE TITLE
Missing subtitles with multiple SwitchRow elements

### ISSUE THREAD

**Issue by dnicolson** [bcylin/QuickTableViewController#50]
When using multiple SwitchRow elements, subtitles can be hidden at random.

In the following [example](https://github.com/dnicolson/QuickTableViewController/blob/8374a10785913eb25b5869c4dd530143e5df7ffc/Example-iOS/ViewControllers/ExampleViewController.swift#L46) the "Setting14" row is missing the subtitle:

<img width="280" alt="Screen Shot 2020-06-25 at 18 28 42" src="https://user-images.githubusercontent.com/2276355/85760731-69c47b00-b712-11ea-9339-f40bb0276b9c.png">

This has been tested in the following environments:
Xcode 11.3.1 (11C504) on macOS 10.14.6 (18G3020)
Xcode 11.5 (11E608c) on macOS 11.0 Beta (20A4299v)

This looks like it may be an Apple bug as the behaviour is somewhat erratic.

**Comment by bcylin** [comment]
@dnicolson thanks much for spotting this bug! 👍 

I think it's caused by the same cell reuse identifier that's set to different cell types.

In the sample code you provide, the first row's cell style is `.default` while the other rows are `.subtitle`. But their cell reuse identifiers are all the same `T.cellIdentifier`. When the first cell is reused for another row after scrolling, its detail text label is not properly displayed.

I added a fix at 2976336. Please let me know if this solves the problem. Thanks!

**Comment by dnicolson** [comment]
Looks good to me, thanks for the quick fix!
