### ISSUE TITLE
How to get the modernUI with rounded corners? 🧐

### ISSUE THREAD

**Issue by keshaaaav** [bcylin/QuickTableViewController#95]
First of all, thank you so much for this!

I was testing the *Demo* build and it has this modern UI with rounded corners — It looks pretty nice!

![Simulator Screen Shot - iPad (8th generation) - 2021-06-18 at 02 24 19](https://user-images.githubusercontent.com/83570000/122471236-a4d35480-cfdc-11eb-8b0a-e9a57cb44440.png)

but, after adding the dependency, I set the whole thing up (by adding ```tableContents``` in ```viewDidLoad```) but I have this old UI with sharp corners

![Simulator Screen Shot - iPad (8th generation) - 2021-06-18 at 02 24 28](https://user-images.githubusercontent.com/83570000/122471828-5ecac080-cfdd-11eb-80a5-faa825e7069e.png)

I scratched my head for sometime and realized I might want to add this:

```
 init() {
    if #available(iOS 13.0, *) {
      super.init(style: .insetGrouped)
    } else {
      super.init(style: .grouped)
    }

    let titleLabel = UILabel()
    titleLabel.text = "QuickTableViewController"
    titleLabel.font = UIFont.boldSystemFont(ofSize: 17)
    title = " "
    navigationItem.titleView = titleLabel
  }

  required init?(coder: NSCoder) {
    fatalError("init(coder:) has not been implemented") }
```

because this was the only thing that was **not** in my code but it was **present** in demo build, but my app crashes with a Fatal Error init(coder:) has not been implemented

Thank you.

**Comment by bcylin** [comment]
Thanks for using QuickTableViewController.

The UI with rounded corners is [UITableView.Style.insetGrouped](https://developer.apple.com/documentation/uikit/uitableview/style/insetgrouped), which requires iOS 13+. The default table view style is `.grouped` because QuickTableViewController still supports iOS 8. You can use [`QuickTableViewController.init(style:)`](https://bcylin.github.io/QuickTableViewController/Classes/QuickTableViewController.html#/s:24QuickTableViewControllerAAC5styleABSo07UITableC5StyleV_tcfc) to initilise the view controller in code with a different style.

https://github.com/bcylin/QuickTableViewController/blob/29fbe93277cdfa2f5fa088cb93a10cf0035f3124/Source/QuickTableViewController.swift#L35-L36

But I guess you are using a storyboard so the view controller is initialised via `init?(coder:)`. The demo app in the project does not have the implementation for storyboards. That's why there's the fatal error from the demo code you copied.

One solution for storyboards is to override the table view after the initialisation from `init?(coder:)`. The frame does not matter here because the layout is set up during [`viewDidLoad()`](https://github.com/bcylin/QuickTableViewController/blob/29fbe93277cdfa2f5fa088cb93a10cf0035f3124/Source/QuickTableViewController.swift#L78-L82).

```swift
required init?(coder: NSCoder) {
  super.init(coder: coder)
  if #available(iOS 13.0, *) {
    tableView = UITableView(frame: .zero, style: .insetGrouped)
  }
}
```

Hope this helps.
